### ISSUE TITLE
output visualizations

### ISSUE THREAD

**Issue by Daniel63656** [NetEase/Polyphonic-TrOMR#3]
How were the output visualizations generated from the tokens? I ask because I noticed musical errors like different note-types (e.g. eight and quarter) in a chord. Also, when several different note-types are predicted like in 1.png bar 2 (eighth., whole) which must go in two separate voices, how do you decide which voice gets continued by the next tokens? Is it always the shorter one? Do you handle proper voice segregation? Couldn't find this info in the paper either.
It seems to me that some kind of algorithm must have been used to arrive at the output notation from the predicted tokens.

**Comment by wayne-chen** [comment]
Is there any way of rendering the output from the txt semantic representation to sheet music image? In `examples`, there is a `<number>.png` and `<number>.txt`, where I'm guessing the `txt` file gets rendered to the `png` file.

**Comment by Daniel63656** [comment]
From the paper it is not clear how a token representation like they use it, which is an adaptation of Alfaro et al's "Advance position encoding" can even be used to recover voice leadings. Keep in mind that that encoding was created for monophonic music in which case it makes perfect sense. I don't know why the authors do not explain in their paper how and if they properly adapted this encoding to polyphony (the word 'voice" never appears in their paper). That together with their being no actual way to do this in the repo as well raises some suspicions about their claim for this being a true solution to polyphonic music honestly

**Comment by liebharc** [comment]
Hi @Daniel63656 , I think there is a possible confusion about the term polyphony. The [English Wikipedia](https://en.wikipedia.org/wiki/Polyphony) defines polyphony as multiple voices, which you seem to do as well. In contrast to that, the [German Wikipedia](https://de.wikipedia.org/wiki/Polyphonie) mentions that the term can be used in multiple ways, and one of them is that a single instrument plays multiple tones at the same time. So there seems to be different definitions and possibly a cultural aspect to it as well. I don't know about the background of the authors, but the paper clearly is able to handle multiple tones at the same time and demonstrates that with the code provided.

**Comment by liebharc** [comment]
For your original question: You could convert the output to e.g. MusicXML and then run it through MuseScore for a visualization. Likely the same approach would work with Vexflow.

**Comment by Daniel63656** [comment]
Ah thanks for clarifying. I was indeed referring to multiple voices. Then there is no problem indeed.
